# Generated by Django 2.2.6 on 2020-01-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=25)),
                ('sound', models.CharField(max_length=25)),
                ('number_of_legs', models.IntegerField()),
            ],
        ),
    ]
