# Generated by Django 2.2.6 on 2020-01-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=25)),
                ('founded_at', models.DateTimeField()),
                ('founded_by', models.CharField(max_length=25)),
            ],
        ),
    ]
