# Generated by Django 3.0.2 on 2020-02-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyapp', '0004_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filmmaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active_since', models.DateField(max_length=255)),
            ],
        ),
    ]
